
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fss-manage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""       # 동적 생성 방지
  volumeName: fss-manage-pv     # 기존 PV에 바인딩
