apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-generator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-generator
  template:
    metadata:
      labels:
        app: trace-generator
    spec:
      containers:
      - name: trace-generator
        image: jaegertracing/example-hotrod:1.22
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        env:
        - name: JAEGER_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:14268/api/traces"
        - name: JAEGER_AGENT_HOST
          value: "tempo.monitoring.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: "const"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: trace-generator
  namespace: monitoring
spec:
  selector:
    app: trace-generator
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
