
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-fss-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""       # 동적 생성 방지
  volumeName: jenkins-fss-pv     # 기존 PV에 바인딩
