### kubectl patch pv prometheus-fss-pv -p '{"spec":{"claimRef": null}}'
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-postgresql-data-0
  namespace: monitoring
  labels:
    app: postgres-fss-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""       # 동적 생성 방지
  volumeName: postgres-fss-pv     # 기존 PV에 바인딩
