apiVersion: v1
kind: Secret
metadata:
  name: oci-credentials
  namespace: ai-recipe
type: Opaque
stringData:
  privatekey: |
    -----BEGIN RSA PRIVATE KEY-----
    # OCI API Private Key를 여기에 입력하세요
    -----END RSA PRIVATE KEY-----
